/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { LensProvider } from "@lens-protocol/react";

import { TRPCReactProvider } from "~/trpc/react";
import { HydrateClient } from "../trpc/server";
import Wrapper from "./_components/Wrapper";
import { ThirdwebProvider } from "thirdweb/react";
import { lensclient } from "../app/lens/client";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} `}>
      <body>
        <TRPCReactProvider>
          <ThirdwebProvider>
            {children}
            <HydrateClient>
              <Wrapper>{children}</Wrapper>
            </HydrateClient>
          </ThirdwebProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
